spring.application.name=Bocra-Hackathon
spring.datasource.url=jdbc:mysql://localhost:3306/railway?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security Configuration
bocra.security.encryption.key=6fa8c9e5b2a4d3f10123456789abcdef
